// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: barberias.sql

package db

import (
	"context"
	"time"
)

const createBarberia = `-- name: CreateBarberia :one
INSERT INTO barberias (nombre, slug, hora_apertura, hora_cierre)
VALUES ($1, $2, $3, $4)
RETURNING id, nombre, slug, hora_apertura, hora_cierre, activa
`

type CreateBarberiaParams struct {
	Nombre       string    `json:"nombre"`
	Slug         string    `json:"slug"`
	HoraApertura time.Time `json:"hora_apertura"`
	HoraCierre   time.Time `json:"hora_cierre"`
}

func (q *Queries) CreateBarberia(ctx context.Context, arg CreateBarberiaParams) (Barberia, error) {
	row := q.db.QueryRowContext(ctx, createBarberia,
		arg.Nombre,
		arg.Slug,
		arg.HoraApertura,
		arg.HoraCierre,
	)
	var i Barberia
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Slug,
		&i.HoraApertura,
		&i.HoraCierre,
		&i.Activa,
	)
	return i, err
}

const getBarberiaBySlug = `-- name: GetBarberiaBySlug :one
SELECT id, nombre, slug, hora_apertura, hora_cierre, activa
FROM barberias
WHERE slug = $1
  AND activa = true
`

func (q *Queries) GetBarberiaBySlug(ctx context.Context, slug string) (Barberia, error) {
	row := q.db.QueryRowContext(ctx, getBarberiaBySlug, slug)
	var i Barberia
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Slug,
		&i.HoraApertura,
		&i.HoraCierre,
		&i.Activa,
	)
	return i, err
}

const listBarberosByBarberia = `-- name: ListBarberosByBarberia :many
SELECT id, nombre
FROM usuarios
WHERE barberia_id = $1
  AND rol = 'barbero'
  AND activo = true
ORDER BY nombre
`

type ListBarberosByBarberiaRow struct {
	ID     int32  `json:"id"`
	Nombre string `json:"nombre"`
}

func (q *Queries) ListBarberosByBarberia(ctx context.Context, barberiaID int32) ([]ListBarberosByBarberiaRow, error) {
	rows, err := q.db.QueryContext(ctx, listBarberosByBarberia, barberiaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBarberosByBarberiaRow
	for rows.Next() {
		var i ListBarberosByBarberiaRow
		if err := rows.Scan(&i.ID, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
