// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: servicios.sql

package db

import (
	"context"
)

const createServicio = `-- name: CreateServicio :one
INSERT INTO servicios (
  barberia_id, nombre, duracion_minutos, precio
)
VALUES ($1, $2, $3, $4)
RETURNING id, barberia_id, nombre, duracion_minutos, precio, activo
`

type CreateServicioParams struct {
	BarberiaID      int32  `json:"barberia_id"`
	Nombre          string `json:"nombre"`
	DuracionMinutos int32  `json:"duracion_minutos"`
	Precio          string `json:"precio"`
}

func (q *Queries) CreateServicio(ctx context.Context, arg CreateServicioParams) (Servicio, error) {
	row := q.db.QueryRowContext(ctx, createServicio,
		arg.BarberiaID,
		arg.Nombre,
		arg.DuracionMinutos,
		arg.Precio,
	)
	var i Servicio
	err := row.Scan(
		&i.ID,
		&i.BarberiaID,
		&i.Nombre,
		&i.DuracionMinutos,
		&i.Precio,
		&i.Activo,
	)
	return i, err
}

const deactivateServicio = `-- name: DeactivateServicio :exec
UPDATE servicios
SET activo = false
WHERE id = $1
  AND barberia_id = $2
`

type DeactivateServicioParams struct {
	ID         int32 `json:"id"`
	BarberiaID int32 `json:"barberia_id"`
}

func (q *Queries) DeactivateServicio(ctx context.Context, arg DeactivateServicioParams) error {
	_, err := q.db.ExecContext(ctx, deactivateServicio, arg.ID, arg.BarberiaID)
	return err
}

const getServicioByID = `-- name: GetServicioByID :one
SELECT id, barberia_id, nombre, duracion_minutos, precio, activo
FROM servicios
WHERE id = $1
  AND activo = true
`

func (q *Queries) GetServicioByID(ctx context.Context, id int32) (Servicio, error) {
	row := q.db.QueryRowContext(ctx, getServicioByID, id)
	var i Servicio
	err := row.Scan(
		&i.ID,
		&i.BarberiaID,
		&i.Nombre,
		&i.DuracionMinutos,
		&i.Precio,
		&i.Activo,
	)
	return i, err
}

const listServicios = `-- name: ListServicios :many
SELECT id, barberia_id, nombre, duracion_minutos, precio, activo
FROM servicios
WHERE barberia_id = $1
  AND activo = true
ORDER BY nombre
`

func (q *Queries) ListServicios(ctx context.Context, barberiaID int32) ([]Servicio, error) {
	rows, err := q.db.QueryContext(ctx, listServicios, barberiaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Servicio
	for rows.Next() {
		var i Servicio
		if err := rows.Scan(
			&i.ID,
			&i.BarberiaID,
			&i.Nombre,
			&i.DuracionMinutos,
			&i.Precio,
			&i.Activo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiciosByBarberia = `-- name: ListServiciosByBarberia :many
SELECT id, nombre, duracion_minutos, precio
FROM servicios
WHERE barberia_id = $1
  AND activo = true
ORDER BY nombre
`

type ListServiciosByBarberiaRow struct {
	ID              int32  `json:"id"`
	Nombre          string `json:"nombre"`
	DuracionMinutos int32  `json:"duracion_minutos"`
	Precio          string `json:"precio"`
}

func (q *Queries) ListServiciosByBarberia(ctx context.Context, barberiaID int32) ([]ListServiciosByBarberiaRow, error) {
	rows, err := q.db.QueryContext(ctx, listServiciosByBarberia, barberiaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServiciosByBarberiaRow
	for rows.Next() {
		var i ListServiciosByBarberiaRow
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.DuracionMinutos,
			&i.Precio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
