// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usuarios.sql

package db

import (
	"context"
)

const createUsuario = `-- name: CreateUsuario :one
INSERT INTO usuarios (
  barberia_id, nombre, apellido, email, password_hash, rol
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, barberia_id, nombre, apellido, username, email, password_hash, rol, activo
`

type CreateUsuarioParams struct {
	BarberiaID   int32  `json:"barberia_id"`
	Nombre       string `json:"nombre"`
	Apellido     string `json:"apellido"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Rol          string `json:"rol"`
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUsuario,
		arg.BarberiaID,
		arg.Nombre,
		arg.Apellido,
		arg.Email,
		arg.PasswordHash,
		arg.Rol,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.BarberiaID,
		&i.Nombre,
		&i.Apellido,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.Activo,
	)
	return i, err
}

const getUsuarioByEmail = `-- name: GetUsuarioByEmail :one
SELECT id, barberia_id, nombre, apellido, username, email, password_hash, rol, activo
FROM usuarios
WHERE email = $1
  AND activo = true
`

func (q *Queries) GetUsuarioByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuarioByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.BarberiaID,
		&i.Nombre,
		&i.Apellido,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.Activo,
	)
	return i, err
}

const getUsuarioByUsername = `-- name: GetUsuarioByUsername :one
SELECT id, barberia_id, nombre, apellido, username, email, password_hash, rol, activo
FROM usuarios
WHERE username = $1
  AND activo = true
`

func (q *Queries) GetUsuarioByUsername(ctx context.Context, username string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUsuarioByUsername, username)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.BarberiaID,
		&i.Nombre,
		&i.Apellido,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.Activo,
	)
	return i, err
}

const listBarberos = `-- name: ListBarberos :many
SELECT id, nombre, apellido
FROM usuarios
WHERE barberia_id = $1
  AND rol = 'barbero'
  AND activo = true
ORDER BY nombre
`

type ListBarberosRow struct {
	ID       int32  `json:"id"`
	Nombre   string `json:"nombre"`
	Apellido string `json:"apellido"`
}

func (q *Queries) ListBarberos(ctx context.Context, barberiaID int32) ([]ListBarberosRow, error) {
	rows, err := q.db.QueryContext(ctx, listBarberos, barberiaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBarberosRow
	for rows.Next() {
		var i ListBarberosRow
		if err := rows.Scan(&i.ID, &i.Nombre, &i.Apellido); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
